version: 2
updates:
  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: daily
    ignore:
      - dependency-name: "github.com/aws/aws-sdk-go-v2"
        update-types: ["version-update:semver-patch"]
      - dependency-name: "github.com/aws/aws-sdk-go-v2/config"
        update-types: ["version-update:semver-patch"]
      - dependency-name: "github.com/aws/aws-sdk-go-v2/feature/s3/manager"
        update-types: ["version-update:semver-patch"]
      - dependency-name: "github.com/aws/aws-sdk-go-v2/service/ec2"
        update-types: ["version-update:semver-patch"]
      - dependency-name: "github.com/aws/aws-sdk-go-v2/service/s3"
        update-types: ["version-update:semver-patch"]
