kind: pipeline
type: kubernetes
name: test

steps:
  - name: Build
    image: golang:1.18
    commands:
      - apt-get update && apt-get install -y protobuf-compiler
      - go mod download
      - go install google.golang.org/protobuf/cmd/protoc-gen-go@v1.28
      - go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@v1.2
      - go install github.com/golang/mock/mockgen@v1.6.0
      - go generate ./...
      - go test ./...

