name: Manager Build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:

  build:
    name: linux build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - name: Setup protoc
        uses: arduino/setup-protoc@v1.1.2

      - name: Download Dependencies
        run: go mod download

      - name: Generate
        run: |
          go install google.golang.org/protobuf/cmd/protoc-gen-go@v1.28
          go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@v1.2
          go generate golang.anshulg.com/popcorntime/go_encoder/api/proto

      - name: Build
        run: go build -v -ldflags "-s -w" golang.anshulg.com/popcorntime/go_encoder/cmd/manager

      - name: Archive artifacts
        uses: actions/upload-artifact@v3
        with:
          name: manager
          path: manager